### ISSUE TITLE
The minOccurs value for 'publisher' in  the complex type 'elementType' does not match v1.0 of the guidelines

### ISSUE THREAD

**Issue by j-benn** [scholix/schema#2]
In Scholix Guidelines v1.0, the Publisher element in 'Table 2 - Source and Target Object properties' is shown as having the multiplicity of 0..1

However, in [scholix.xsd](https://github.com/scholix/schema/blob/master/xsd/scholix.xsd#L90) line 90 it appears to be 1?
<xs:element minOccurs="1" maxOccurs="1" name="publisher" type="scholix:providerType">

**Comment by luosolo** [comment]
fixed on 76adc3508f39095f6c483d4e2fb72cf37695e0bc
