### ISSUE TITLE
Typo in scholix schema

### ISSUE THREAD

**Issue by minhd** [scholix/schema#4]
In https://github.com/scholix/schema/blob/master/xsd/scholix.xsd

The element `<xs:element name="relashionship" type="scholix:relationshipType" minOccurs="0"maxOccurs="unbounded"/>` should be correctly named `relationship`

and `<xs:element name="inverseRelashionship" minOccurs="0" maxOccurs="1" type="xs:string"/>` should be correctly named `inverseRelationship`

**Comment by minhd** [comment]
I've created a PR to fix this issue at https://github.com/scholix/schema/pull/5

**Comment by luosolo** [comment]
Fixed Typo in https://github.com/scholix/schema/blob/master/xsd/v1/scholix.xsd
